### ISSUE TITLE
Adriana eroSa kahpelik yaptın hilenin sonu geldi öç 

### ISSUE THREAD

**Issue by QuenssLand** [KoMaR1911/C4USMultiHack-Metin2#18]
Oc komar

**Comment by Timurleng06** [comment]
ondanmı kapandı  c4us.pl sitesi ?

**Comment by Timurleng06** [comment]
eros ile adriana nasıl ulaşırız onlar yapıyor mu hile ?

**Comment by QuenssLand** [comment]
Evet bu komar tek kelime bile yazmadan hilede hiç bi katkısı olmadan adamların gizli sourcelarinı dağıttı. Onlarda herkesin elinde olan birşeyi geliştirmeme kararı alıp bıraktı

**Comment by Timurleng06** [comment]
bu komar Türk diyorlar doğrumu ?

**Comment by Timurleng06** [comment]
bu arkadaslar yapamaz mı birdaha hile felan ? Adrian eros felan

**Comment by Timurleng06** [comment]
Bu arkadaşa Türk diyorlardı.

**Comment by Timurleng06** [comment]
bu öç güncelleyecek ozaman hileyi

**Comment by idrisjoyyu** [comment]
adamlar parayla satıyordu komar'da beleşe verince hileyi ortalık karıştı ayağa düştü hile, çoluk çocuk köyde adam toplayıp sektirmeye başladı. millet edebiyle meleyini boss u nu kesse bu kadar yaygara olmazdı

**Comment by Timurleng06** [comment]
m2bob alacaz artık hile güncellenmyecekse

**Comment by byturko** [comment]
e şimdi kim güncelliyecek hileyi ?

**Comment by Timurleng06** [comment]
Adrian yada eroS ulaşmak lazım bu arkadaşlara.  CheatGlobal dakiler ulaşamaz mı bunlara söyleseler yaparlarmı ki parası neyse veririz

**Comment by Timurleng06** [comment]
Adrian ile eroS ulaşmak lazım.

**Comment by Timurleng06** [comment]
CheatGlobal'daki adminler ulaşamazlar mı bunlara ?

**Comment by QuenssLand** [comment]
Beyler bunu yapanların hiç biri guncellemez forumu kapatıp kocaman yazı yazmışlar 3 kişilerdi bu komar hilenin dosyalarını paylaştı. Diğer ikiside herkesin elinde olan dosyalar için birdaha uğraşmayacagini artık guncellemeyecegini ve üstüne ekleyip geliştirmeyecegini duyurdu. Bu piçde artık guncellemeyecegim diyo. Yani anlayan biri guncellerse günceller yoksa bitti bu hile.

**Comment by QuenssLand** [comment]
Bu komarin dağıttığı dosyalar çok kişinin elinde var artık bir yazılımcı bulup guncelletip kendimi kullanir yada herhangi bi forumda anlayan biri guncelleyip millet ile paylaşırmi bı fikrim yok ama hilenin dosyaları pic oldu herkesin elinde. Güncellemeyi bilen kim varsa o kullancak

**Comment by Timurleng06** [comment]
cheatglobal yapsınlar

**Comment by KoMaR1911** [comment]
Updated! - 18.06.2021 to latest Global update!

**Comment by KoMaR1911** [comment]
Updated! - 18.06.2021 to latest Global update!
