### ISSUE TITLE
i need windows 7 ?

### ISSUE THREAD

**Issue by cosmin2205** [KoMaR1911/C4USMultiHack-Metin2#26]
hello, to compile i need win 7 ?

**Comment by KoMaR1911** [comment]
why?

**Comment by cosmin2205** [comment]
at first i thought i am getting that thousand errors because of the windows sdk and i need lower versions of windows sdk which im not able to get, i am very new to c++ and vc and i'm doing my best.. after some researches i found that getting a mac vm could be an option ? https://www.py4u.net/discuss/83763
