### ISSUE TITLE
Can we use other skills like poisonous cloud

### ISSUE THREAD

**Issue by MehmetAran** [KoMaR1911/C4USMultiHack-Metin2#4]
Hi Komar, I saw a section that is skill number section in the cheat. I think we can use other skills like poisonous cloud. Then I started to try a warrior skills, but game was crushed. So i can't do it. Can we do it or it is just a bug for poisonous cloud? Thank you ❤

**Comment by KoMaR1911** [comment]
No

**Comment by MehmetAran** [comment]
So is this skill a bug, right?
